
spring:
  liquibase:
    change-log: "classpath:/db/changelog/changelog-master.xml"
    enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/search_engine?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: q1w2e3r4t5A1
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    h2:
      console:
        enabled: true
  web:
    resources:
      static-locations: classpath:/search_engine_frontend/

  thymeleaf:
    prefix: classpath:/search_engine_frontend/

url:
  sites:
    - url: http://www.playback.ru
      name: playback
    - url: https://dombulgakova.ru
      name: hh
user-Agent: Mozilla/5.0 (Windows; U; WindowsNT 5.1; en-US; rv1.8.1.6) Gecko/20070725 Firefox/2.0.0.6
web-interface: /admin
server:
  port: 8083
#url:
#  sites:
#    - https://www.lenta.ru
#    - http://www.playback.ru

